<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>PhotoKeepKill</RootNamespace>
    <AssemblyName>Keeply</AssemblyName>
    <Version>1.0.5</Version>
    <AssemblyVersion>1.0.5.0</AssemblyVersion>
    <FileVersion>1.0.5.0</FileVersion>
    <ApplicationIcon>assets\Keeply.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="3.119.4" />
    <Content Include="licensing.json" CopyToOutputDirectory="PreserveNewest" />
    <Resource Include="assets\Keeply.ico" />
  </ItemGroup>
</Project>
